// Static assets setup

// Tooltips for each graph
var map_tip = d3.select("#map")
    .append("div")
    .style("opacity", 1)
    .attr("class", "tooltip")
    .style("background-color", "white")
    .style("border", "solid")
    .style("border-width", "2px")
    .style("border-radius", "5px")
    .style("padding", "5px")
    .style("position", "absolute")
    .style("opacity", 0)
    .raise()

var pie_tip = d3.select("#pie")
    .append("div")
    .style("opacity", 1)
    .attr("class", "tooltip")
    .style("background-color", "white")
    .style("border", "solid")
    .style("border-width", "2px")
    .style("border-radius", "5px")
    .style("padding", "5px")
    .style("position", "absolute")
    .style("opacity", 0)
    .raise()

var line_tip = d3.select("#line")
    .append("div")
    .style("opacity", 1)
    .attr("class", "tooltip")
    .style("background-color", "white")
    .style("border", "solid")
    .style("border-width", "2px")
    .style("border-radius", "5px")
    .style("padding", "5px")
    .style("position", "absolute")
    .style("opacity", 0)
    .raise()

// create pie
let pie_svg = d3.select("#pie")
    .append("svg")
    .attr("width", 600)
    .attr("height", 500)

let pie = pie_svg.append('g')
    .attr('transform', 'translate(300, 300)')


pie_svg.append("text")
    .attr("x", 175)
    .attr("y", 100)
    .text("Annual Greenhouse Gas Emissions")
pie_svg.append("circle")
    .attr("cx", 490)
    .attr("cy", 396)
    .attr("r", 5)
    .attr("fill", "crimson")
pie_svg.append("text")
    .attr("x", 500)
    .attr("y", 400)
    .attr("id", "co2box")
    .style("font-size", "14px")

pie_svg.append("circle")
    .attr("cx", 490)
    .attr("cy", 410)
    .attr("r", 5)
    .attr("fill", "magenta")
pie_svg.append("text")
    .attr("x", 500)
    .attr("y", 414)
    .attr("id", "ch4box")
    .style("font-size", "14px")

pie_svg.append("circle")
    .attr("cx", 490)
    .attr("cy", 424)
    .attr("r", 5)
    .attr("fill", "orange")
pie_svg.append("text")
    .attr("x", 500)
    .attr("y", 428)
    .attr("id", "n2obox")
    .style("font-size", "14px")

pie_svg.append("text")
    .attr("x", 500)
    .attr("y", 442)
    .attr("id", "totalbox")
    .style("font-size", "14px")
/*
// add Y axis
var scat_y = d3.scaleLinear()
    .domain([0, 750000])
    .range([ 500, 0]);
scatter.append("g")
    .attr("id", "scatoutcome")
    .attr("transform", "translate(100, 50)")
    .call(d3.axisLeft(scat_y));

// add text elements
scatter_svg.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", 380)
    .attr("y", 600)
    .text("GDP per capita");
scatter_svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("x", -225)
    .attr("y", 25)
    .attr("dy", ".75em")
    .attr("transform", "rotate(-90)")
    .text("Cases per million");
*/
// create linegraph
let line_svg = d3.select("#line")
    .append("svg")
    .attr("width", 600)
    .attr("height", 300)
let line = line_svg.append("g")
    .attr("id", "linegraph")

// add text elements
line_svg.append("text")
    .attr("x", 375)
    .attr("y", 18)
    .attr("text-anchor", "middle")
    .text("Fossil Fuel Production")
    .style("font-weight", "box")
line_svg.append("text")
    .attr("x", 110)
    .attr("y", 18)
    .attr("id", "datebox")
    .style("font-size", "14px")
line_svg.append('circle')
    .attr('cx', 110)
    .attr('cy', 28)
    .attr('r', 5)
    .style('fill', 'purple')
line_svg.append("text")
    .attr("x", 120)
    .attr("y", 32)
    .attr("id", "oilbox")
    .style("font-size", "14px")
line_svg.append('circle')
    .attr('cx', 110)
    .attr('cy', 42)
    .attr('r', 5)
    .style('fill', 'steelblue')
line_svg.append("text")
    .attr("x", 120)
    .attr("y", 46)
    .attr("id", "coalbox")
    .style("font-size", "14px")
line_svg.append('circle')
    .attr('cx', 110)
    .attr('cy', 56)
    .attr('r', 5)
    .style('fill', 'green')
line_svg.append("text")
    .attr("x", 120)
    .attr("y", 60)
    .attr("id", "gasbox")
    .style("font-size", "14px")
line_svg.append("text")
    .attr("class", "x label")
    .attr("text-anchor", "end")
    .attr("x", 395)
    .attr("y", 290)
    .text("Year");
line_svg.append("text")
    .attr("class", "y label")
    .attr("text-anchor", "end")
    .attr("x", -25)
    .attr("y", 25)
    .attr("dy", ".75em")
    .attr("transform", "rotate(-90)")
    .text("Production (TWh)");

let info_svg = d3.select('#info')
    .append('svg')
    .attr('width', 600)
    .attr('height', 300)    
info_svg.append("text")
    .attr("x", 300)
    .attr("y", 100)
    .attr("id", "linetitle")
    .attr("text-anchor", "middle")
    .style("font-weight", 700)
    .style("font-size", 24)
    .text("GBP")
info_svg.append("text")
    .attr("x", 300)
    .attr("y", 150)
    .attr("text-anchor", "middle")
    .attr("id", "gdprank")
    .text("# in GDP")
    .style("font-weight", 700)
info_svg.append("text")
    .attr("x", 300)
    .attr("y", 200)
    .attr("text-anchor", "middle")
    .attr("id", "poprank")
    .text("% of global population")
    .style("font-weight", 700)
